In [1]:
import pandas as pd

In [4]:
df = pd.read_parquet("wyniki")

In [5]:
df

,proc_time,event_time,temperature,location
0,2023-06-02 17:02:00.452,02-06-2023 17:02:00:452059,72.461975,Hala Katowice
1,2023-06-02 17:03:48.606,02-06-2023 17:03:48:606729,32.434856,Hala Katowice
2,2023-06-02 17:02:56.535,02-06-2023 17:02:56:535282,33.477428,Hala Katowice
3,2023-06-02 17:03:28.581,02-06-2023 17:03:28:581274,94.661858,Hala Katowice
4,2023-06-02 17:04:24.743,02-06-2023 17:04:24:743418,92.515915,Hala Katowice
...,...,...,...,...
58,2023-06-02 17:01:12.382,02-06-2023 17:01:12:381944,57.963730,Hala Katowice
59,2023-06-02 17:01:20.393,02-06-2023 17:01:20:393714,20.450497,Hala Katowice
60,2023-06-02 17:04:36.759,02-06-2023 17:04:36:759694,85.152565,Hala Katowice
61,2023-06-02 17:04:52.779,02-06-2023 17:04:52:779597,15.723300,Hala Katowice
62,2023-06-02 17:01:44.427,02-06-2023 17:01:44:427071,90.837982,Hala Katowice